# This file was generated by GoReleaser. DO NOT EDIT.
class Anchorectl < Formula
  desc "A CLI tool for interacting with Anchore"
  homepage "https://github.com/anchore/anchorectl"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/anchore/anchorectl/releases/download/v0.0.1/anchorectl_0.0.1_darwin_amd64.tar.gz"
    sha256 "9d1305b1b05bf50b3a0659bfd34426595739e7c46dd8b11147ca67c4ad2e81b6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/anchore/anchorectl/releases/download/v0.0.1/anchorectl_0.0.1_linux_amd64.tar.gz"
      sha256 "58b00419a3d7ec01c2c7af2fc9d5e6085e4b4c5433c30ae9487d47cd2df14fde"
    end
  end

  def install
    bin.install "anchorectl"
  end
end
