# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Anchorectl < Formula
  desc "A CLI tool for interacting with Anchore"
  homepage "https://github.com/anchore/anchorectl"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/anchorectl/releases/download/v0.2.0/anchorectl_0.2.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fd5187ec893b192065c8c4243f9fde63ba2f8623efce46e80818c39d2028aef0"

      def install
        bin.install "anchorectl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/anchorectl/releases/download/v0.2.0/anchorectl_0.2.0_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "5e62f7e3140252b95c2a63c1c72031bb30ef2ef1ff62c6f33f83fc40f05f44d2"

      def install
        bin.install "anchorectl"
      end
    end
  end
end
