# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Anchorectl < Formula
  desc "A CLI tool for interacting with Anchore"
  homepage "https://github.com/anchore/anchorectl"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/anchore/anchorectl/releases/download/v0.1.1/anchorectl_0.1.1_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "0d40573d3fe1118d3ec5e10f8c7e7010a371c7dcc2c95e61d3730945822cc3b6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/anchore/anchorectl/releases/download/v0.1.1/anchorectl_0.1.1_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2bbf7526537009a2b83c058b15e034a2e030edcc0b89b65157328dc406db5ee0"
    end
  end

  def install
    bin.install "anchorectl"
  end
end
